### ISSUE TITLE
ERROR - Config value: 'plugins'. Error: Invalid config options for the "mkpdfs" plugin.

### ISSUE THREAD

**Issue by avarone-github** [comwes/mkpdfs-mkdocs-plugin#5]
**mkdocs build** gives this error:

```
ERROR - Config value: 'plugins'. Error: Invalid config options for the "mkpdfs" plugin.
```

when mkdocs.yml has this configuration:

```
plugins:
    - search
    - mkpdfs:
        - author: Pippo
```

With this configuration:

```
plugins:
    - search
    - mkpdfs
```

no problem.
According to [the documentation](https://comwes.github.io/mkpdfs-mkdocs-plugin/pdf/documentation.pdf), syntax for the plugin configuration parameter is correct.

**Comment by comwes** [comment]
Hi @avarone-github,

You are right, there's an error in the documentation. I'll update it as soon as possible.
Your should use something like this.:

```
plugins:
    - search
    - mkpdfs:
        author: Pippo
```
KR,
